In [1]:
import numpy as np
import chainer
from chainer import cuda, Function, gradient_check, Variable, optimizers, serializers, utils
from chainer import Link, Chain, ChainList
import chainer.functions as F
import chainer.links as L

In [2]:
x_data = np.array([5], dtype=np.float32)
x = Variable(x_data)

In [6]:
y = x**2 - 2 * x + 1
y.data

array([ 16.], dtype=float32)

In [7]:
y.backward()

In [9]:
x.grad

array([ 8.], dtype=float32)

In [12]:
z = 2*x
y = x**2 - z + 1
y.backward(retain_grad=True)
z.grad

array([ 32.], dtype=float32)

In [13]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32))
y = x**2 - 2*x + 1
y.grad = np.ones((2, 3), dtype=np.float32)
y.backward()
x.grad

array([[  0.,   2.,   4.],
       [  6.,   8.,  10.]], dtype=float32)

In [16]:
f = F.Linear(3, 2)

In [17]:
f.W.data

array([[-0.20027296, -1.05729485,  0.48038578],
       [ 0.13058658,  0.04542512,  0.03335766]], dtype=float32)

In [18]:
f.b.data

array([ 0.,  0.], dtype=float32)

In [19]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32))
y = f(x)
y.data

array([[-0.87370539,  0.32150978],
       [-3.20525122,  0.94961786]], dtype=float32)

In [20]:
f.zerograds()

In [23]:
y.grad = np.ones((2, 2), dtype=np.float32)
y.backward()
f.W.grad
f.b.grad

array([ 6.,  6.], dtype=float32)